### ISSUE TITLE
Cannot find module 'archiver'

### ISSUE THREAD

**Issue by sambshapiro** [rokudev/atomio-package#4]
Copied the instructions exactly from the readme, and when I opened up Atom I get this error:

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: 'atom_roku' package v0.0.1

### Stack Trace

Uncaught Error: Cannot find module 'archiver'

```
At module.js:472

Error: Cannot find module 'archiver'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom_roku/lib/atom_roku.js:2:16)
    at /packages/atom_roku/lib/atom_roku.js:259:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:431:18)
    at new PackageCard (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:92:16)
    at PackageDetailView.completeInitialization (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:206:34)
    at PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
    at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:100:16)
    at callback (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:366:26)
    at SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at SettingsView.showDeferredPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:416:20)
    at SettingsView.initializePanels (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:250:18)
```

### Commands

```
```

### Non-Core Packages

```
atom_roku 0.0.1 
language-brightscript 0.6.3 
node_modules undefined 
```

**Comment by yurii-polishchuk** [comment]
Thank you for your request, but the atomio package was decommissioned and is no longer maintained.
